defaults:
  af-packet:
    interface: ~
    threads: auto
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    mmap-locked: yes
    tpacket-v3: yes
    ring-size: 2048
    block-size: 32768
    block-timeout: 10
    use-emergency-flush: yes
    checksum-checks: kernel
    bfp-filter: ~
    copy-mode: ~
    copy-iface: ~