version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "rust:"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "github-actions:"
    ignore:
      - dependency-name: "actions/cache"
        versions: ["3.x"]
      - dependency-name: "actions/checkout"
        versions: ["3.x"]
