#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

/* automatically generated by rust-bindgen 0.58.1 */

pub const _STDINT_H: u32 = 1;
pub const _FEATURES_H: u32 = 1;
pub const _DEFAULT_SOURCE: u32 = 1;
pub const __GLIBC_USE_ISOC2X: u32 = 0;
pub const __USE_ISOC11: u32 = 1;
pub const __USE_ISOC99: u32 = 1;
pub const __USE_ISOC95: u32 = 1;
pub const __USE_POSIX_IMPLICITLY: u32 = 1;
pub const _POSIX_SOURCE: u32 = 1;
pub const _POSIX_C_SOURCE: u32 = 200809;
pub const __USE_POSIX: u32 = 1;
pub const __USE_POSIX2: u32 = 1;
pub const __USE_POSIX199309: u32 = 1;
pub const __USE_POSIX199506: u32 = 1;
pub const __USE_XOPEN2K: u32 = 1;
pub const __USE_XOPEN2K8: u32 = 1;
pub const _ATFILE_SOURCE: u32 = 1;
pub const __USE_MISC: u32 = 1;
pub const __USE_ATFILE: u32 = 1;
pub const __USE_FORTIFY_LEVEL: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_GETS: u32 = 0;
pub const __GLIBC_USE_DEPRECATED_SCANF: u32 = 0;
pub const _STDC_PREDEF_H: u32 = 1;
pub const __STDC_IEC_559__: u32 = 1;
pub const __STDC_IEC_559_COMPLEX__: u32 = 1;
pub const __STDC_ISO_10646__: u32 = 201706;
pub const __GNU_LIBRARY__: u32 = 6;
pub const __GLIBC__: u32 = 2;
pub const __GLIBC_MINOR__: u32 = 32;
pub const _SYS_CDEFS_H: u32 = 1;
pub const __glibc_c99_flexarr_available: u32 = 1;
pub const __WORDSIZE: u32 = 64;
pub const __WORDSIZE_TIME64_COMPAT32: u32 = 1;
pub const __SYSCALL_WORDSIZE: u32 = 64;
pub const __LDOUBLE_REDIRECTS_TO_FLOAT128_ABI: u32 = 0;
pub const __HAVE_GENERIC_SELECTION: u32 = 1;
pub const __GLIBC_USE_LIB_EXT2: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_BFP_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT: u32 = 0;
pub const __GLIBC_USE_IEC_60559_FUNCS_EXT_C2X: u32 = 0;
pub const __GLIBC_USE_IEC_60559_TYPES_EXT: u32 = 0;
pub const _BITS_TYPES_H: u32 = 1;
pub const __TIMESIZE: u32 = 64;
pub const _BITS_TYPESIZES_H: u32 = 1;
pub const __OFF_T_MATCHES_OFF64_T: u32 = 1;
pub const __INO_T_MATCHES_INO64_T: u32 = 1;
pub const __RLIM_T_MATCHES_RLIM64_T: u32 = 1;
pub const __STATFS_MATCHES_STATFS64: u32 = 1;
pub const __KERNEL_OLD_TIMEVAL_MATCHES_TIMEVAL64: u32 = 1;
pub const __FD_SETSIZE: u32 = 1024;
pub const _BITS_TIME64_H: u32 = 1;
pub const _BITS_WCHAR_H: u32 = 1;
pub const _BITS_STDINT_INTN_H: u32 = 1;
pub const _BITS_STDINT_UINTN_H: u32 = 1;
pub const INT8_MIN: i32 = -128;
pub const INT16_MIN: i32 = -32768;
pub const INT32_MIN: i32 = -2147483648;
pub const INT8_MAX: u32 = 127;
pub const INT16_MAX: u32 = 32767;
pub const INT32_MAX: u32 = 2147483647;
pub const UINT8_MAX: u32 = 255;
pub const UINT16_MAX: u32 = 65535;
pub const UINT32_MAX: u32 = 4294967295;
pub const INT_LEAST8_MIN: i32 = -128;
pub const INT_LEAST16_MIN: i32 = -32768;
pub const INT_LEAST32_MIN: i32 = -2147483648;
pub const INT_LEAST8_MAX: u32 = 127;
pub const INT_LEAST16_MAX: u32 = 32767;
pub const INT_LEAST32_MAX: u32 = 2147483647;
pub const UINT_LEAST8_MAX: u32 = 255;
pub const UINT_LEAST16_MAX: u32 = 65535;
pub const UINT_LEAST32_MAX: u32 = 4294967295;
pub const INT_FAST8_MIN: i32 = -128;
pub const INT_FAST16_MIN: i64 = -9223372036854775808;
pub const INT_FAST32_MIN: i64 = -9223372036854775808;
pub const INT_FAST8_MAX: u32 = 127;
pub const INT_FAST16_MAX: u64 = 9223372036854775807;
pub const INT_FAST32_MAX: u64 = 9223372036854775807;
pub const UINT_FAST8_MAX: u32 = 255;
pub const UINT_FAST16_MAX: i32 = -1;
pub const UINT_FAST32_MAX: i32 = -1;
pub const INTPTR_MIN: i64 = -9223372036854775808;
pub const INTPTR_MAX: u64 = 9223372036854775807;
pub const UINTPTR_MAX: i32 = -1;
pub const PTRDIFF_MIN: i64 = -9223372036854775808;
pub const PTRDIFF_MAX: u64 = 9223372036854775807;
pub const SIG_ATOMIC_MIN: i32 = -2147483648;
pub const SIG_ATOMIC_MAX: u32 = 2147483647;
pub const SIZE_MAX: i32 = -1;
pub const WINT_MIN: u32 = 0;
pub const WINT_MAX: u32 = 4294967295;
pub const true_: u32 = 1;
pub const false_: u32 = 0;
pub const __bool_true_false_are_defined: u32 = 1;
pub const B64_BLOCK: u32 = 4;
pub const SC_MD5_LEN: u32 = 16;
pub const CTNT_IS_MSG: u32 = 1;
pub const CTNT_IS_ENV: u32 = 2;
pub const CTNT_IS_ENCAP: u32 = 4;
pub const CTNT_IS_BODYPART: u32 = 8;
pub const CTNT_IS_MULTIPART: u32 = 16;
pub const CTNT_IS_ATTACHMENT: u32 = 32;
pub const CTNT_IS_BASE64: u32 = 64;
pub const CTNT_IS_QP: u32 = 128;
pub const CTNT_IS_TEXT: u32 = 256;
pub const CTNT_IS_HTML: u32 = 512;
pub const URL_IS_IP4: u32 = 1;
pub const URL_IS_IP6: u32 = 2;
pub const URL_IS_EXE: u32 = 4;
pub const ANOM_INVALID_BASE64: u32 = 1;
pub const ANOM_INVALID_QP: u32 = 2;
pub const ANOM_LONG_HEADER_NAME: u32 = 4;
pub const ANOM_LONG_HEADER_VALUE: u32 = 8;
pub const ANOM_LONG_LINE: u32 = 16;
pub const ANOM_LONG_ENC_LINE: u32 = 32;
pub const ANOM_MALFORMED_MSG: u32 = 64;
pub const ANOM_LONG_BOUNDARY: u32 = 128;
pub const ANOM_LONG_FILENAME: u32 = 256;
pub const DATA_CHUNK_SIZE: u32 = 3072;
pub const LINEREM_SIZE: u32 = 256;
pub const HEADER_READY: u32 = 1;
pub const HEADER_STARTED: u32 = 2;
pub const HEADER_DONE: u32 = 3;
pub const BODY_STARTED: u32 = 4;
pub const BODY_DONE: u32 = 5;
pub const BODY_END_BOUND: u32 = 6;
pub const PARSE_DONE: u32 = 7;
pub const PARSE_ERROR: u32 = 8;
pub type __u_char = ::std::os::raw::c_uchar;
pub type __u_short = ::std::os::raw::c_ushort;
pub type __u_int = ::std::os::raw::c_uint;
pub type __u_long = ::std::os::raw::c_ulong;
pub type __int8_t = ::std::os::raw::c_schar;
pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int16_t = ::std::os::raw::c_short;
pub type __uint16_t = ::std::os::raw::c_ushort;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint32_t = ::std::os::raw::c_uint;
pub type __int64_t = ::std::os::raw::c_long;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type __int_least8_t = __int8_t;
pub type __uint_least8_t = __uint8_t;
pub type __int_least16_t = __int16_t;
pub type __uint_least16_t = __uint16_t;
pub type __int_least32_t = __int32_t;
pub type __uint_least32_t = __uint32_t;
pub type __int_least64_t = __int64_t;
pub type __uint_least64_t = __uint64_t;
pub type __quad_t = ::std::os::raw::c_long;
pub type __u_quad_t = ::std::os::raw::c_ulong;
pub type __intmax_t = ::std::os::raw::c_long;
pub type __uintmax_t = ::std::os::raw::c_ulong;
pub type __dev_t = ::std::os::raw::c_ulong;
pub type __uid_t = ::std::os::raw::c_uint;
pub type __gid_t = ::std::os::raw::c_uint;
pub type __ino_t = ::std::os::raw::c_ulong;
pub type __ino64_t = ::std::os::raw::c_ulong;
pub type __mode_t = ::std::os::raw::c_uint;
pub type __nlink_t = ::std::os::raw::c_ulong;
pub type __off_t = ::std::os::raw::c_long;
pub type __off64_t = ::std::os::raw::c_long;
pub type __pid_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __fsid_t {
    pub __val: [::std::os::raw::c_int; 2usize],
}
#[test]
fn bindgen_test_layout___fsid_t() {
    assert_eq!(
        ::std::mem::size_of::<__fsid_t>(),
        8usize,
        concat!("Size of: ", stringify!(__fsid_t))
    );
    assert_eq!(
        ::std::mem::align_of::<__fsid_t>(),
        4usize,
        concat!("Alignment of ", stringify!(__fsid_t))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<__fsid_t>())).__val as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(__fsid_t),
            "::",
            stringify!(__val)
        )
    );
}
pub type __clock_t = ::std::os::raw::c_long;
pub type __rlim_t = ::std::os::raw::c_ulong;
pub type __rlim64_t = ::std::os::raw::c_ulong;
pub type __id_t = ::std::os::raw::c_uint;
pub type __time_t = ::std::os::raw::c_long;
pub type __useconds_t = ::std::os::raw::c_uint;
pub type __suseconds_t = ::std::os::raw::c_long;
pub type __suseconds64_t = ::std::os::raw::c_long;
pub type __daddr_t = ::std::os::raw::c_int;
pub type __key_t = ::std::os::raw::c_int;
pub type __clockid_t = ::std::os::raw::c_int;
pub type __timer_t = *mut ::std::os::raw::c_void;
pub type __blksize_t = ::std::os::raw::c_long;
pub type __blkcnt_t = ::std::os::raw::c_long;
pub type __blkcnt64_t = ::std::os::raw::c_long;
pub type __fsblkcnt_t = ::std::os::raw::c_ulong;
pub type __fsblkcnt64_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt_t = ::std::os::raw::c_ulong;
pub type __fsfilcnt64_t = ::std::os::raw::c_ulong;
pub type __fsword_t = ::std::os::raw::c_long;
pub type __ssize_t = ::std::os::raw::c_long;
pub type __syscall_slong_t = ::std::os::raw::c_long;
pub type __syscall_ulong_t = ::std::os::raw::c_ulong;
pub type __loff_t = __off64_t;
pub type __caddr_t = *mut ::std::os::raw::c_char;
pub type __intptr_t = ::std::os::raw::c_long;
pub type __socklen_t = ::std::os::raw::c_uint;
pub type __sig_atomic_t = ::std::os::raw::c_int;
pub type int_least8_t = __int_least8_t;
pub type int_least16_t = __int_least16_t;
pub type int_least32_t = __int_least32_t;
pub type int_least64_t = __int_least64_t;
pub type uint_least8_t = __uint_least8_t;
pub type uint_least16_t = __uint_least16_t;
pub type uint_least32_t = __uint_least32_t;
pub type uint_least64_t = __uint_least64_t;
pub type int_fast8_t = ::std::os::raw::c_schar;
pub type int_fast16_t = ::std::os::raw::c_long;
pub type int_fast32_t = ::std::os::raw::c_long;
pub type int_fast64_t = ::std::os::raw::c_long;
pub type uint_fast8_t = ::std::os::raw::c_uchar;
pub type uint_fast16_t = ::std::os::raw::c_ulong;
pub type uint_fast32_t = ::std::os::raw::c_ulong;
pub type uint_fast64_t = ::std::os::raw::c_ulong;
pub type intmax_t = __intmax_t;
pub type uintmax_t = __uintmax_t;
pub const MimeDecRetCode_MIME_DEC_OK: MimeDecRetCode = 0;
pub const MimeDecRetCode_MIME_DEC_MORE: MimeDecRetCode = 1;
pub const MimeDecRetCode_MIME_DEC_ERR_DATA: MimeDecRetCode = -1;
pub const MimeDecRetCode_MIME_DEC_ERR_MEM: MimeDecRetCode = -2;
pub const MimeDecRetCode_MIME_DEC_ERR_PARSE: MimeDecRetCode = -3;
#[doc = "< parser in error state"]
pub const MimeDecRetCode_MIME_DEC_ERR_STATE: MimeDecRetCode = -4;
#[doc = " \\brief Mime Decoder Error Codes"]
pub type MimeDecRetCode = ::std::os::raw::c_int;
#[doc = " \\brief Structure for containing configuration options"]
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MimeDecConfig {
    #[doc = "< Decode base64 bodies"]
    pub decode_base64: ::std::os::raw::c_int,
    #[doc = "< Decode quoted-printable bodies"]
    pub decode_quoted_printable: ::std::os::raw::c_int,
    #[doc = "< Extract and store URLs in data structure"]
    pub extract_urls: ::std::os::raw::c_int,
    #[doc = "< Compute md5 sum of body"]
    pub body_md5: ::std::os::raw::c_int,
    #[doc = "< Depth of which to store header values"]
    #[doc = "(Default is 2000)"]
    pub header_value_depth: u32,
}
#[test]
fn bindgen_test_layout_MimeDecConfig() {
    assert_eq!(
        ::std::mem::size_of::<MimeDecConfig>(),
        20usize,
        concat!("Size of: ", stringify!(MimeDecConfig))
    );
    assert_eq!(
        ::std::mem::align_of::<MimeDecConfig>(),
        4usize,
        concat!("Alignment of ", stringify!(MimeDecConfig))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecConfig>())).decode_base64 as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecConfig),
            "::",
            stringify!(decode_base64)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<MimeDecConfig>())).decode_quoted_printable as *const _ as usize
        },
        4usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecConfig),
            "::",
            stringify!(decode_quoted_printable)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecConfig>())).extract_urls as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecConfig),
            "::",
            stringify!(extract_urls)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecConfig>())).body_md5 as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecConfig),
            "::",
            stringify!(body_md5)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<MimeDecConfig>())).header_value_depth as *const _ as usize
        },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecConfig),
            "::",
            stringify!(header_value_depth)
        )
    );
}
#[doc = " \\brief This represents a header field name and associated value"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MimeDecField {
    #[doc = "< Name of the header field"]
    pub name: *mut u8,
    #[doc = "< Length of the name"]
    pub name_len: u32,
    #[doc = "< Length of the value"]
    pub value_len: u32,
    #[doc = "< Value of the header field"]
    pub value: *mut u8,
    #[doc = "< Pointer to next field"]
    pub next: *mut MimeDecField,
}
#[test]
fn bindgen_test_layout_MimeDecField() {
    assert_eq!(
        ::std::mem::size_of::<MimeDecField>(),
        32usize,
        concat!("Size of: ", stringify!(MimeDecField))
    );
    assert_eq!(
        ::std::mem::align_of::<MimeDecField>(),
        8usize,
        concat!("Alignment of ", stringify!(MimeDecField))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecField>())).name as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecField),
            "::",
            stringify!(name)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecField>())).name_len as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecField),
            "::",
            stringify!(name_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecField>())).value_len as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecField),
            "::",
            stringify!(value_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecField>())).value as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecField),
            "::",
            stringify!(value)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecField>())).next as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecField),
            "::",
            stringify!(next)
        )
    );
}
#[doc = " \\brief This represents a URL value node in a linked list"]
#[doc = ""]
#[doc = " Since HTML can sometimes contain a high number of URLs, this"]
#[doc = " structure only features the URL host name/IP or those that are"]
#[doc = " pointing to an executable file (see url_flags to determine which)."]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MimeDecUrl {
    #[doc = "< String representation of full or partial URL (lowercase)"]
    pub url: *mut u8,
    #[doc = "< Length of the URL string"]
    pub url_len: u32,
    #[doc = "< Flags indicating type of URL"]
    pub url_flags: u32,
    #[doc = "< Pointer to next URL"]
    pub next: *mut MimeDecUrl,
}
#[test]
fn bindgen_test_layout_MimeDecUrl() {
    assert_eq!(
        ::std::mem::size_of::<MimeDecUrl>(),
        24usize,
        concat!("Size of: ", stringify!(MimeDecUrl))
    );
    assert_eq!(
        ::std::mem::align_of::<MimeDecUrl>(),
        8usize,
        concat!("Alignment of ", stringify!(MimeDecUrl))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecUrl>())).url as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecUrl),
            "::",
            stringify!(url)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecUrl>())).url_len as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecUrl),
            "::",
            stringify!(url_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecUrl>())).url_flags as *const _ as usize },
        12usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecUrl),
            "::",
            stringify!(url_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecUrl>())).next as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecUrl),
            "::",
            stringify!(next)
        )
    );
}
#[doc = " \\brief This represents the MIME Entity (or also top level message) in a"]
#[doc = " child-sibling tree"]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MimeDecEntity {
    #[doc = "< Pointer to list of header fields"]
    pub field_list: *mut MimeDecField,
    #[doc = "< Pointer to list of URLs"]
    pub url_list: *mut MimeDecUrl,
    #[doc = "< Length of body (prior to any decoding)"]
    pub body_len: u32,
    #[doc = "< Length of body after decoding"]
    pub decoded_body_len: u32,
    #[doc = "< Flags indicating header characteristics"]
    pub header_flags: u32,
    #[doc = "< Flags indicating type of content"]
    pub ctnt_flags: u32,
    #[doc = "< Flags indicating an anomaly in the message"]
    pub anomaly_flags: u32,
    #[doc = "< Length of file attachment name"]
    pub filename_len: u32,
    #[doc = "< Name of file attachment"]
    pub filename: *mut u8,
    #[doc = "< Quick access pointer to short-hand content type field"]
    pub ctnt_type: *mut u8,
    #[doc = "< Length of content type field value"]
    pub ctnt_type_len: u32,
    #[doc = "< Quick access pointer to message Id"]
    pub msg_id_len: u32,
    #[doc = "< Quick access pointer to message Id"]
    pub msg_id: *mut u8,
    #[doc = "< Pointer to list of sibling entities"]
    pub next: *mut MimeDecEntity,
    #[doc = "< Pointer to list of child entities"]
    pub child: *mut MimeDecEntity,
}
#[test]
fn bindgen_test_layout_MimeDecEntity() {
    assert_eq!(
        ::std::mem::size_of::<MimeDecEntity>(),
        88usize,
        concat!("Size of: ", stringify!(MimeDecEntity))
    );
    assert_eq!(
        ::std::mem::align_of::<MimeDecEntity>(),
        8usize,
        concat!("Alignment of ", stringify!(MimeDecEntity))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).field_list as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(field_list)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).url_list as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(url_list)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).body_len as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(body_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).decoded_body_len as *const _ as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(decoded_body_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).header_flags as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(header_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).ctnt_flags as *const _ as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(ctnt_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).anomaly_flags as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(anomaly_flags)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).filename_len as *const _ as usize },
        36usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(filename_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).filename as *const _ as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(filename)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).ctnt_type as *const _ as usize },
        48usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(ctnt_type)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).ctnt_type_len as *const _ as usize },
        56usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(ctnt_type_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).msg_id_len as *const _ as usize },
        60usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(msg_id_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).msg_id as *const _ as usize },
        64usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(msg_id)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).next as *const _ as usize },
        72usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(next)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecEntity>())).child as *const _ as usize },
        80usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecEntity),
            "::",
            stringify!(child)
        )
    );
}
#[doc = " \\brief Structure contains boundary and entity for the current node (entity)"]
#[doc = " in the stack"]
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MimeDecStackNode {
    #[doc = "< Pointer to the entity data structure"]
    pub data: *mut MimeDecEntity,
    #[doc = "< Copy of boundary definition for child entity"]
    pub bdef: *mut u8,
    #[doc = "< Boundary length for child entity"]
    pub bdef_len: u32,
    #[doc = "< Flag indicating entity is encapsulated in message"]
    pub is_encap: ::std::os::raw::c_int,
    #[doc = "< Pointer to next item on the stack"]
    pub next: *mut MimeDecStackNode,
}
#[test]
fn bindgen_test_layout_MimeDecStackNode() {
    assert_eq!(
        ::std::mem::size_of::<MimeDecStackNode>(),
        32usize,
        concat!("Size of: ", stringify!(MimeDecStackNode))
    );
    assert_eq!(
        ::std::mem::align_of::<MimeDecStackNode>(),
        8usize,
        concat!("Alignment of ", stringify!(MimeDecStackNode))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecStackNode>())).data as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecStackNode),
            "::",
            stringify!(data)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecStackNode>())).bdef as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecStackNode),
            "::",
            stringify!(bdef)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecStackNode>())).bdef_len as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecStackNode),
            "::",
            stringify!(bdef_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecStackNode>())).is_encap as *const _ as usize },
        20usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecStackNode),
            "::",
            stringify!(is_encap)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecStackNode>())).next as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecStackNode),
            "::",
            stringify!(next)
        )
    );
}
#[doc = " \\brief Structure holds the top of the stack along with some free reusable nodes"]
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MimeDecStack {
    #[doc = "< Pointer to the top of the stack"]
    pub top: *mut MimeDecStackNode,
    #[doc = "< Pointer to the list of free nodes"]
    pub free_nodes: *mut MimeDecStackNode,
    #[doc = "< Count of free nodes in the list"]
    pub free_nodes_cnt: u32,
}
#[test]
fn bindgen_test_layout_MimeDecStack() {
    assert_eq!(
        ::std::mem::size_of::<MimeDecStack>(),
        24usize,
        concat!("Size of: ", stringify!(MimeDecStack))
    );
    assert_eq!(
        ::std::mem::align_of::<MimeDecStack>(),
        8usize,
        concat!("Alignment of ", stringify!(MimeDecStack))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecStack>())).top as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecStack),
            "::",
            stringify!(top)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecStack>())).free_nodes as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecStack),
            "::",
            stringify!(free_nodes)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecStack>())).free_nodes_cnt as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecStack),
            "::",
            stringify!(free_nodes_cnt)
        )
    );
}
#[doc = " \\brief Structure contains a list of value and lengths for robust data processing"]
#[doc = ""]
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DataValue {
    #[doc = "< Copy of data value"]
    pub value: *mut u8,
    #[doc = "< Length of data value"]
    pub value_len: u32,
    #[doc = "< Pointer to next value in the list"]
    pub next: *mut DataValue,
}
#[test]
fn bindgen_test_layout_DataValue() {
    assert_eq!(
        ::std::mem::size_of::<DataValue>(),
        24usize,
        concat!("Size of: ", stringify!(DataValue))
    );
    assert_eq!(
        ::std::mem::align_of::<DataValue>(),
        8usize,
        concat!("Alignment of ", stringify!(DataValue))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<DataValue>())).value as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(DataValue),
            "::",
            stringify!(value)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<DataValue>())).value_len as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(DataValue),
            "::",
            stringify!(value_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<DataValue>())).next as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(DataValue),
            "::",
            stringify!(next)
        )
    );
}
#[doc = " \\brief Structure contains the current state of the MIME parser"]
#[doc = ""]
#[repr(C)]
#[derive(Copy, Clone)]
pub struct MimeDecParseState {
    #[doc = "< Pointer to the top-level message entity"]
    pub msg: *mut MimeDecEntity,
    #[doc = "< Pointer to the top of the entity stack"]
    pub stack: *mut MimeDecStack,
    #[doc = "< Copy of the last known header name"]
    pub hname: *mut u8,
    #[doc = "< Length of the last known header name"]
    pub hlen: u32,
    #[doc = "< Total length of value list"]
    pub hvlen: u32,
    #[doc = "< Pointer to the incomplete header value list"]
    pub hvalue: *mut DataValue,
    #[doc = "< Remainder from previous line (for URL extraction)"]
    pub linerem: [u8; 256usize],
    #[doc = "< Length of remainder from previous line"]
    pub linerem_len: u16,
    #[doc = "< Remainder from base64-decoded line"]
    pub bvremain: [u8; 4usize],
    #[doc = "< Length of remainder from base64-decoded line"]
    pub bvr_len: u8,
    #[doc = "< Buffer holding data chunk"]
    pub data_chunk: [u8; 3072usize],
    pub md5_ctx: *mut ::std::os::raw::c_void,
    pub md5: [u8; 16usize],
    pub has_md5: bool,
    #[doc = "<  Flag representing current state of parser"]
    pub state_flag: u8,
    #[doc = "< Length of data chunk"]
    pub data_chunk_len: u32,
    #[doc = "< Flag indicating a child entity was found"]
    pub found_child: ::std::os::raw::c_int,
    #[doc = "< Currently at beginning of body"]
    pub body_begin: ::std::os::raw::c_int,
    #[doc = "< Currently at end of body"]
    pub body_end: ::std::os::raw::c_int,
    #[doc = "< Length of line delimiter"]
    pub current_line_delimiter_len: u8,
    #[doc = "< Pointer to data specific to the caller"]
    pub data: *mut ::std::os::raw::c_void,
    pub DataChunkProcessorFunc: ::std::option::Option<
        unsafe extern "C" fn(
            chunk: *const u8,
            len: u32,
            state: *mut MimeDecParseState,
        ) -> ::std::os::raw::c_int,
    >,
}
#[test]
fn bindgen_test_layout_MimeDecParseState() {
    assert_eq!(
        ::std::mem::size_of::<MimeDecParseState>(),
        3440usize,
        concat!("Size of: ", stringify!(MimeDecParseState))
    );
    assert_eq!(
        ::std::mem::align_of::<MimeDecParseState>(),
        8usize,
        concat!("Alignment of ", stringify!(MimeDecParseState))
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).msg as *const _ as usize },
        0usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(msg)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).stack as *const _ as usize },
        8usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(stack)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).hname as *const _ as usize },
        16usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(hname)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).hlen as *const _ as usize },
        24usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(hlen)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).hvlen as *const _ as usize },
        28usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(hvlen)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).hvalue as *const _ as usize },
        32usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(hvalue)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).linerem as *const _ as usize },
        40usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(linerem)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).linerem_len as *const _ as usize },
        296usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(linerem_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).bvremain as *const _ as usize },
        298usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(bvremain)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).bvr_len as *const _ as usize },
        302usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(bvr_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).data_chunk as *const _ as usize },
        303usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(data_chunk)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).md5_ctx as *const _ as usize },
        3376usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(md5_ctx)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).md5 as *const _ as usize },
        3384usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(md5)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).has_md5 as *const _ as usize },
        3400usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(has_md5)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).state_flag as *const _ as usize },
        3401usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(state_flag)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<MimeDecParseState>())).data_chunk_len as *const _ as usize
        },
        3404usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(data_chunk_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).found_child as *const _ as usize },
        3408usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(found_child)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).body_begin as *const _ as usize },
        3412usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(body_begin)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).body_end as *const _ as usize },
        3416usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(body_end)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<MimeDecParseState>())).current_line_delimiter_len as *const _
                as usize
        },
        3420usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(current_line_delimiter_len)
        )
    );
    assert_eq!(
        unsafe { &(*(::std::ptr::null::<MimeDecParseState>())).data as *const _ as usize },
        3424usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(data)
        )
    );
    assert_eq!(
        unsafe {
            &(*(::std::ptr::null::<MimeDecParseState>())).DataChunkProcessorFunc as *const _
                as usize
        },
        3432usize,
        concat!(
            "Offset of field: ",
            stringify!(MimeDecParseState),
            "::",
            stringify!(DataChunkProcessorFunc)
        )
    );
}
extern "C" {
    pub fn MimeDecSetConfig(config: *mut MimeDecConfig);
}
extern "C" {
    pub fn MimeDecGetConfig() -> *mut MimeDecConfig;
}
extern "C" {
    pub fn MimeDecFreeEntity(entity: *mut MimeDecEntity);
}
extern "C" {
    pub fn MimeDecFreeField(field: *mut MimeDecField);
}
extern "C" {
    pub fn MimeDecFreeUrl(url: *mut MimeDecUrl);
}
extern "C" {
    pub fn MimeDecAddField(entity: *mut MimeDecEntity) -> *mut MimeDecField;
}
extern "C" {
    pub fn MimeDecFindField(
        entity: *const MimeDecEntity,
        name: *const ::std::os::raw::c_char,
    ) -> *mut MimeDecField;
}
extern "C" {
    pub fn MimeDecFindFieldsForEach(
        entity: *const MimeDecEntity,
        name: *const ::std::os::raw::c_char,
        DataCallback: ::std::option::Option<
            unsafe extern "C" fn(
                val: *const u8,
                size_t: ::std::os::raw::c_int,
                data: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn MimeDecAddEntity(parent: *mut MimeDecEntity) -> *mut MimeDecEntity;
}
extern "C" {
    pub fn MimeDecInitParser(
        data: *mut ::std::os::raw::c_void,
        dcpfunc: ::std::option::Option<
            unsafe extern "C" fn(
                chunk: *const u8,
                len: u32,
                state: *mut MimeDecParseState,
            ) -> ::std::os::raw::c_int,
        >,
    ) -> *mut MimeDecParseState;
}
extern "C" {
    pub fn MimeDecDeInitParser(state: *mut MimeDecParseState);
}
extern "C" {
    pub fn MimeDecParseComplete(state: *mut MimeDecParseState) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn MimeDecParseLine(
        line: *const u8,
        len: u32,
        delim_len: u8,
        state: *mut MimeDecParseState,
    ) -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn MimeDecParseFullMsg(
        buf: *const u8,
        blen: u32,
        data: *mut ::std::os::raw::c_void,
        DataChunkProcessorFunc: ::std::option::Option<
            unsafe extern "C" fn(
                chunk: *const u8,
                len: u32,
                state: *mut MimeDecParseState,
            ) -> ::std::os::raw::c_int,
        >,
    ) -> *mut MimeDecEntity;
}
extern "C" {
    pub fn MimeDecParseStateGetStatus(
        state: *mut MimeDecParseState,
    ) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn MimeDecRegisterTests();
}
