name: Post Authors

on:
  workflow_run:
    workflows:
      - New Author Check
    types:
      - completed

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this runs after the author check"
      # - uses: actions/download-artifact@9782bd6a9848b53b110e712e20e42d89988822b7
      #   with:
      #     name: new-authors
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "new-authors"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/new-authors.zip`, Buffer.from(download.data));
      - name: unzip
        run: unzip new-authors.zip
      - run: cat new-authors.txt
      - run: |
          if [[ "$(cat new-authors.txt | wc -l)" != 0 ]]; then
              echo has_new_authors=yes >> $GITHUB_ENV
          fi
      - if: ${{ env.has_new_authors == 'yes' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          retries: 3
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This pull request contains *NEW* authors.'
            })
      - if: ${{ env.has_new_authors != 'yes' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          retries: 3
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'This pull request contains NO new authors.'
            })
      
        
