name: Scan-build

on:
  push:
    paths-ignore:
      - "doc/**"
      - "etc/schema.json"
  pull_request:
    paths-ignore:
      - "doc/**"
      - "etc/schema.json"

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan-build:
    name: Scan-build
    runs-on: ubuntu-latest
    container: ubuntu:26.04
    steps:
      - name: Cache scan-build
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57
        with:
          path: ~/.cargo
          key: scan-build
      - run: apt update && apt -y install git
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Build with scan-build
        run: ./qa/ci/scan-build.sh
      - name: 'Upload Scan Build Results'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: scan-build-results
          path: scan-build-report/
          retention-days: 5

